#ifndef CONSTANTS_H
#define CONSTANTS_H

/*
 * Problem: CGO reads object files to determine the type of constants.
 * It does not understand preprocessor defines.
 * Constants cannot be defined in the header since they must be defined exactly once.
 * So they are declared as symbols to be resolved externally.
 * Then constants.c defines them and the external linker puts it all together.
 * This way, both cgo and gcc can access the values.
 */
#ifndef CHARCONSTANT
#define CHARCONSTANT(key, value) extern const char * key
#endif

/*
 * String keys for user-configurable settings.
 */
CHARCONSTANT(GOWHATSAPP_FETCH_CONTACTS_AFTER_LINKING_OPTION, "fetch-contacts-after-linking");
CHARCONSTANT(GOWHATSAPP_REQUEST_CONTACTS_AFTER_LOGIN_OPTION, "request-contacts-after-login");
CHARCONSTANT(GOWHATSAPP_UPDATE_BUDDY_ON_MESSAGE_OPTION, "update-buddy-on-message");
CHARCONSTANT(GOWHATSAPP_FAKE_ONLINE_OPTION, "fake-online");
CHARCONSTANT(GOWHATSAPP_QRCODE_SIZE_OPTION, "qrcode-size");
CHARCONSTANT(GOWHATSAPP_SEND_RECEIPT_OPTION, "send-receipt");
CHARCONSTANT(GOWHATSAPP_ICONS_OPTION, "get-icons");
CHARCONSTANT(GOWHATSAPP_EXPIRATION_OPTION, "message-expiration");
CHARCONSTANT(GOWHATSAPP_HANDLE_IMAGES_OPTION, "handle-images");
CHARCONSTANT(GOWHATSAPP_GROUP_IS_FILE_ORIGIN_OPTION, "group-is-file-origin");
CHARCONSTANT(GOWHATSAPP_AUTO_JOIN_CHAT_OPTION, "autojoin-chats");
CHARCONSTANT(GOWHATSAPP_BRIDGE_COMPATIBILITY_OPTION, "bridge-compatibility");
CHARCONSTANT(GOWHATSAPP_DISPLAY_MESSAGE_ID_OPTION, "display-message-id");
CHARCONSTANT(GOWHATSAPP_ECHO_OPTION, "echo-sent-messages");
CHARCONSTANT(GOWHATSAPP_MESSAGE_CACHE_SIZE_OPTION, "message-cache-size");
CHARCONSTANT(GOWHATSAPP_IGNORE_STATUS_BROADCAST_OPTION, "ignore-status-broadcast");
CHARCONSTANT(GOWHATSAPP_IGNORE_NEWSLETTERS_OPTION, "ignore-newsletters");
CHARCONSTANT(GOWHATSAPP_INLINE_ALL_IMAGES_OPTION, "inline-all-images");
CHARCONSTANT(GOWHATSAPP_DISCARD_OLD_MESSAGES_OPTION, "discard-old-messages");
CHARCONSTANT(GOWHATSAPP_EMBED_MAX_FILE_SIZE_OPTION, "embed-max-file-size");
CHARCONSTANT(GOWHATSAPP_TRUSTED_URL_REGEX_OPTION, "trusted-url-regex");
CHARCONSTANT(GOWHATSAPP_TRUSTED_URL_REGEX_DEFAULT, "");
CHARCONSTANT(GOWHATSAPP_DEVICE_NAME_OPTION, "device-name");
CHARCONSTANT(GOWHATSAPP_DEVICE_NAME_DEFAULT, "purple-whatsmeow on %s");
CHARCONSTANT(GOWHATSAPP_DATABASE_ADDRESS_OPTION, "database-address");
CHARCONSTANT(GOWHATSAPP_DATABASE_ADDRESS_DEFAULT, "file:$purple_user_dir/whatsmeow.db?_pragma=foreign_keys(1)&_pragma=busy_timeout(3000)&_pragma=journal_mode(WAL)");
CHARCONSTANT(GOWHATSAPP_ATTACHMENT_PATH_TEMPLATE_OPTION, "attachment-path-template");
CHARCONSTANT(GOWHATSAPP_ATTACHMENT_PATH_TEMPLATE_DEFAULT, "");
CHARCONSTANT(GOWHATSAPP_ATTACHMENT_URL_TEMPLATE_OPTION, "attachment-url-template");
CHARCONSTANT(GOWHATSAPP_ATTACHMENT_URL_TEMPLATE_DEFAULT, "");
CHARCONSTANT(GOWHATSAPP_ATTACHMENT_SYMLINK_OPTION, "attachment-symlink");
CHARCONSTANT(GOWHATSAPP_FETCH_HISTORY_OPTION, "fetch-history-on-open");

/*
 * Choices for GOWHATSAPP_SEND_RECEIPT_OPTION.
 */
CHARCONSTANT(GOWHATSAPP_SEND_RECEIPT_CHOICE_IMMEDIATELY, "immediately");
CHARCONSTANT(GOWHATSAPP_SEND_RECEIPT_CHOICE_ON_INTERACT, "on-interact");
CHARCONSTANT(GOWHATSAPP_SEND_RECEIPT_CHOICE_ON_ANSWER, "on-answer");
CHARCONSTANT(GOWHATSAPP_SEND_RECEIPT_CHOICE_NEVER, "never");

/*
 * Choices for GOWHATSAPP_HANDLE_IMAGES_OPTION.
 */
CHARCONSTANT(GOWHATSAPP_HANDLE_IMAGES_CHOICE_BOTH, "both");
CHARCONSTANT(GOWHATSAPP_HANDLE_IMAGES_CHOICE_INLINE, "inline");
CHARCONSTANT(GOWHATSAPP_HANDLE_IMAGES_CHOICE_ATTACHMENT, "xfer");


/*
 * Choices for GOWHATSAPP_CLIENT_APPEARANCE_OPTION.
 */
CHARCONSTANT(GOWHATSAPP_CLIENT_APPEARANCE_CHOICE_DEFAULT, "default");
CHARCONSTANT(GOWHATSAPP_CLIENT_APPEARANCE_CHOICE_ONLINE, "appear-online");
CHARCONSTANT(GOWHATSAPP_CLIENT_APPEARANCE_CHOICE_OFFLINE, "appear-offline");

/*
 * Choices for GOWHATSAPP_ECHO_OPTION.
 */
CHARCONSTANT(GOWHATSAPP_ECHO_CHOICE_ON_SUCCESS, "on-success");
CHARCONSTANT(GOWHATSAPP_ECHO_CHOICE_INTERNAL, "internal");
CHARCONSTANT(GOWHATSAPP_ECHO_CHOICE_IMMEDIATELY, "immediately");
CHARCONSTANT(GOWHATSAPP_ECHO_CHOICE_NEVER, "never");

/*
 * Choices for GOWHATSAPP_ICONS_OPTION.
 */
CHARCONSTANT(GOWHATSAPP_ICONS_CHOICE_NO, "no");
CHARCONSTANT(GOWHATSAPP_ICONS_CHOICE_PREVIEW, "preview");
CHARCONSTANT(GOWHATSAPP_ICONS_CHOICE_ORIGINAL, "original");

/*
 * Keys for account data.
 */
CHARCONSTANT(GOWHATSAPP_CREDENTIALS_KEY, "credentials");
CHARCONSTANT(GOWHATSAPP_PRESENCE_OVERRIDE_KEY, "presence-override");
#endif
