package main

/*
#include "constants.h"
*/
import "C"

import (
	"encoding/json"
	"os"
	"strings"
	"time"

	"go.mau.fi/whatsmeow/proto/waE2E"
	"go.mau.fi/whatsmeow/types"
)

type CachedMessage struct {
	ID        types.MessageID
	Chat      types.JID
	Sender    types.JID
	Timestamp time.Time
	Message   waE2E.Message
}

/*
 * Add a message to the message cache to it can be looked up later.
 * Useful for replying to a specific message and for displaying relevant information when dealing with reactions.
 */
func (handler *Handler) add_to_cache(message *waE2E.Message, id types.MessageID, chat types.JID, sender types.JID, timestamp time.Time) {
	if message.GetReactionMessage() != nil {
		// ReactionMessage cannot be referred to, do not cache
		return
	}
	//handler.log.Infof("add_to_cache: %s %#v", id, message)
	etm := message.ExtendedTextMessage
	if etm != nil && etm.ContextInfo != nil && etm.ContextInfo.QuotedMessage != nil {
		// TODO: find out which fields of message are actually needed for creating qouted messages
		etm.ContextInfo.QuotedMessage.MessageContextInfo = nil
	}
	handler.cachedMessages = append(handler.cachedMessages, CachedMessage{
		// an in-place copy of the message must be created field-by-field due to protobuf demanding exclusive authority or something (mutexes are involved)
		Message: waE2E.Message{
			Conversation:          message.Conversation,
			ExtendedTextMessage:   etm,
			ImageMessage:          message.ImageMessage,
			VideoMessage:          message.VideoMessage,
			PtvMessage:            message.PtvMessage,
			AudioMessage:          message.AudioMessage,
			StickerMessage:        message.StickerMessage,
			DocumentMessage:       message.DocumentMessage,
			PollCreationMessage:   message.PollCreationMessage,
			PollCreationMessageV2: message.PollCreationMessageV2,
			PollCreationMessageV3: message.PollCreationMessageV3,
			PollCreationMessageV5: message.PollCreationMessageV5,
		},
		ID:        id,
		Chat:      chat,
		Sender:    sender,
		Timestamp: timestamp,
		// TODO: also add FromMe and IsGroup since they are necessary for BuildPollVote
	})
	// from https://www.delftstack.com/howto/go/queue-implementation-in-golang/
	if len(handler.cachedMessages) > purple_get_int(handler.account, C.GOWHATSAPP_MESSAGE_CACHE_SIZE_OPTION, 0) {
		handler.cachedMessages = handler.cachedMessages[1:]
	}
}

func (handler *Handler) lookup_cached_message_by_id(id string) *CachedMessage {
	for i := range handler.cachedMessages {
		if handler.cachedMessages[i].ID == id {
			return &handler.cachedMessages[i]
		}
	}
	return nil
}

func (handler *Handler) lookup_cached_message_by_substring(chat types.JID, needle string) *CachedMessage {
	for i := len(handler.cachedMessages) - 1; i >= 0; i-- {
		//handler.log.Infof("lookup: „%s“ is „%s“: %v", handler.cachedMessages[i].Chat.ToNonAD(), chat.ToNonAD(), handler.cachedMessages[i].Chat.ToNonAD() == chat.ToNonAD())
		if handler.cachedMessages[i].Chat.ToNonAD() == chat.ToNonAD() {
			message := &handler.cachedMessages[i].Message
			conversation := message.GetConversation()
			text := message.GetExtendedTextMessage().GetText()
			//handler.log.Infof("lookup „%s“ in „%s“: %v or in „%s“: %v", needle, conversation, strings.Contains(conversation, needle), text, strings.Contains(text, needle))
			if strings.Contains(conversation, needle) || strings.Contains(text, needle) {
				return &handler.cachedMessages[i]
			}
		}
	}
	return nil
}

// generated by ChatGPT
func (handler *Handler) SaveCachedMessages(filePath string) {
	file, err := os.Create(filePath)
	if err != nil {
		handler.log.Errorf("Failed to create cached messages file: %v", err)
		return
	}
	defer file.Close()
	data, err := json.Marshal(handler.cachedMessages)
	if err != nil {
		handler.log.Errorf("Failed to marshal cached messages to JSON: %v", err)
		return
	}
	_, err = file.Write(data)
	if err != nil {
		handler.log.Errorf("Failed to write cached messages to file: %v", err)
		return
	}
}

// generated by ChatGPT
func (handler *Handler) LoadCachedMessages(filePath string) {
	file, err := os.Open(filePath)
	if err != nil {
		handler.log.Errorf("Failed to open cached messages file: %v", err)
		return
	}
	defer file.Close()
	data, err := os.ReadFile(filePath)
	if err != nil {
		handler.log.Errorf("Failed to read cached messages file: %v", err)
		return
	}
	var cachedMessages []CachedMessage
	err = json.Unmarshal(data, &cachedMessages)
	if err != nil {
		handler.log.Errorf("Failed to unmarshal cached messages: %v", err)
		return
	}
	handler.cachedMessages = cachedMessages
	handler.log.Infof("Loaded %d cached messages.", len(cachedMessages))
}
