package main

/*
#include "constants.h"
*/
import "C"

import (
	"encoding/json"
	"os"
	"time"

	"go.mau.fi/whatsmeow/proto/waE2E"
	"go.mau.fi/whatsmeow/types"
)

type CachedMessage struct {
	Message   waE2E.Message
	ID        types.MessageID
	Timestamp time.Time
	Sender    types.JID
}

/*
 * Add a message to the message cache to it can be looked up later.
 * Useful for replying to a specific message and for displaying relevant information when dealing with reactions.
 */
func (handler *Handler) add_to_cache(message *waE2E.Message, id types.MessageID, timestamp time.Time, sender types.JID) {
	handler.cachedMessages = append(handler.cachedMessages, CachedMessage{
		// an in-place copy of the message must be created due to protobuf relying on exclusive access
		Message: waE2E.Message{
			// TODO: find out which fields of message are actually needed for creating qouted messages
			Conversation:        message.Conversation,
			ExtendedTextMessage: message.ExtendedTextMessage,
			ImageMessage:        message.ImageMessage,
			VideoMessage:        message.VideoMessage,
			PtvMessage:          message.PtvMessage,
			AudioMessage:        message.AudioMessage,
			StickerMessage:      message.StickerMessage,
			DocumentMessage:     message.DocumentMessage,
		},
		ID:        id,
		Timestamp: timestamp,
		Sender:    sender,
	})
	// from https://www.delftstack.com/howto/go/queue-implementation-in-golang/
	if len(handler.cachedMessages) > purple_get_int(handler.account, C.GOWHATSAPP_MESSAGE_CACHE_SIZE_OPTION, 1000) {
		handler.cachedMessages = handler.cachedMessages[1:]
	}
}

func (handler *Handler) lookup_cached_message_by_id(id string) *CachedMessage {
	// TODO: check whether the look-up does work for outgoing image messages
	// TODO: add/check all kinds of outgoing messages (I do not remember if text-messages are already working)
	for i := range handler.cachedMessages {
		if handler.cachedMessages[i].ID == id {
			return &handler.cachedMessages[i]
		}
	}
	return nil
}

// generated by ChatGPT
func (handler *Handler) SaveCachedMessages(filePath string) {
	file, err := os.Create(filePath)
	if err != nil {
		handler.log.Errorf("Failed to create cached messages file: %v", err)
		return
	}
	defer file.Close()
	data, err := json.Marshal(handler.cachedMessages)
	if err != nil {
		handler.log.Errorf("Failed to marshal cached messages to JSON: %v", err)
		return
	}
	_, err = file.Write(data)
	if err != nil {
		handler.log.Errorf("Failed to write cached messages to file: %v", err)
		return
	}
}

// generated by ChatGPT
func (handler *Handler) LoadCachedMessages(filePath string) {
	file, err := os.Open(filePath)
	if err != nil {
		handler.log.Errorf("Failed to open cached messages file: %v", err)
		return
	}
	defer file.Close()
	data, err := os.ReadFile(filePath)
	if err != nil {
		handler.log.Errorf("Failed to read cached messages file: %v", err)
		return
	}
	var cachedMessages []CachedMessage
	err = json.Unmarshal(data, &cachedMessages)
	if err != nil {
		handler.log.Errorf("Failed to unmarshal cached messages: %v", err)
		return
	}
	handler.cachedMessages = cachedMessages
	handler.log.Infof("Loaded %d cached messages.", len(cachedMessages))
}
