/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/hoehermann/purple-gowhatsapp/src/go */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 24 "bridge.go"

#include "constants.h"
#include "bridge.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void gowhatsapp_go_login(PurpleAccount* account, char* purple_user_dir, char* username, char* password, char* proxy_uri);
extern void gowhatsapp_go_close(PurpleAccount* account);
extern void gowhatsapp_go_logout(PurpleAccount* account);
extern GoInt gowhatsapp_go_send_message(PurpleAccount* account, char* who, char* message, int is_group);
extern char* gowhatsapp_go_send_file(PurpleAccount* account, char* who, char* filename);
extern void gowhatsapp_go_mark_read_conversation(PurpleAccount* account, char* who);
extern void gowhatsapp_go_send_presence(PurpleAccount* account, char* presence);
extern void gowhatsapp_go_subscribe_presence(PurpleAccount* account, char* who);
extern char** gowhatsapp_go_query_group_participants(PurpleAccount* account, char* groupid);
extern void gowhatsapp_go_query_groups(PurpleAccount* account);
extern void gowhatsapp_go_get_contacts(PurpleAccount* account);
extern void gowhatsapp_go_request_profile_picture(PurpleAccount* account, char* who, char* picture_date, char* picture_id);

#ifdef __cplusplus
}
#endif
